# UAS Machine Learning 2019
## Marisha Salsabila
16/394091/PA/17182

In [140]:
import pandas as pd

data = pd.read_excel('labor.xls', encoding = 'ISO-8859-1')

# 1. Soal dibawah ini dijawab mengunakan File labor.xls

a) Buat summary dari atribut-atribut bertipe kontinyu dengan cara menampilkan nilai-nilai count, mean, max, min, std, dan kuartil

In [96]:
data.describe()

duration  wage-increase-first-year  wage-increase-second-year  \
count  56.000000                 56.000000                  46.000000   
mean    2.160714                  3.803571                   3.971739   
std     0.707795                  1.370596                   1.164028   
min     1.000000                  2.000000                   2.000000   
25%     2.000000                  2.500000                   3.000000   
50%     2.000000                  4.000000                   4.000000   
75%     3.000000                  4.500000                   4.500000   
max     3.000000                  7.000000                   7.000000   

       wage-increase-third-year  working-hours  standby-pay  \
count                 15.000000      51.000000     9.000000   
mean                   3.913333      38.039216     7.444444   
std                    1.304315       2.505680     5.027701   
min                    2.000000      27.000000     2.000000   
25%                    2.400000      37.000000     2.000000   
50%                    4.600000      38.000000     8.000000   
75%                    5.000000      40.000000    12.000000   
max                    5.100000      40.000000    14.000000   

       shift-differential  statutory-holidays  
count           31.000000           53.000000  
mean             4.870968           11.094340  
std              4.544168            1.259795  
min              0.000000            9.000000  
25%              3.000000           10.000000  
50%              4.000000           11.000000  
75%              5.000000           12.000000  
max             25.000000           15.000000

b) Tampilikan jumlah missing value setiap atribut dan replace missing value

In [97]:
data.columns

Index(['duration', 'wage-increase-first-year', 'wage-increase-second-year',
       'wage-increase-third-year', 'cost-of-living-adjustment',
       'working-hours', 'pension', 'standby-pay', 'shift-differential',
       'education-allowance', 'statutory-holidays', 'vacation',
       'longterm-disability-assistance', 'contribution-to-dental-plan',
       'bereavement-assistance', 'contribution-to-health-plan', 'class'],
      dtype='object')

In [98]:
print(data.duration.isnull().sum())
print(data['wage-increase-first-year'].isnull().sum())
print(data['wage-increase-second-year'].isnull().sum())
print(data['wage-increase-third-year'].isnull().sum())
print(data['cost-of-living-adjustment'].isnull().sum())
print(data['working-hours'].isnull().sum())
print(data['pension'].isnull().sum())
print(data['standby-pay'].isnull().sum())
print(data['shift-differential'].isnull().sum())
print(data['education-allowance'].isnull().sum())
print(data['statutory-holidays'].isnull().sum())
print(data['vacation'].isnull().sum())
print(data['longterm-disability-assistance'].isnull().sum())
print(data['contribution-to-dental-plan'].isnull().sum())
print(data['bereavement-assistance'].isnull().sum())
print(data['contribution-to-health-plan'].isnull().sum())
print(data['class'].isnull().sum())

1
1
11
42
20
6
30
48
26
35
4
6
29
20
27
20
0


In [99]:
data.duration.median()

2.0

In [100]:
data = data.fillna(data.median())

In [101]:
print(data.duration.isnull().sum())
print(data['wage-increase-first-year'].isnull().sum())
print(data['wage-increase-second-year'].isnull().sum())
print(data['wage-increase-third-year'].isnull().sum())
print(data['cost-of-living-adjustment'].isnull().sum())
print(data['working-hours'].isnull().sum())
print(data['pension'].isnull().sum())
print(data['standby-pay'].isnull().sum())
print(data['shift-differential'].isnull().sum())
print(data['education-allowance'].isnull().sum())
print(data['statutory-holidays'].isnull().sum())
print(data['vacation'].isnull().sum())
print(data['longterm-disability-assistance'].isnull().sum())
print(data['contribution-to-dental-plan'].isnull().sum())
print(data['bereavement-assistance'].isnull().sum())
print(data['contribution-to-health-plan'].isnull().sum())
print(data['class'].isnull().sum())

0
0
0
0
20
0
30
0
0
35
0
6
29
20
27
20
0


In [52]:
#untuk data kategorikal diganti dengan mean
#ubah ke numerik dengan label encoding


In [102]:
data['cost-of-living-adjustment'].value_counts()
data['cost-of-living-adjustment'] = data['cost-of-living-adjustment'].fillna('none') 

In [84]:
data['cost-of-living-adjustment'].unique()

array([nan, 'tc', 'none', 'tcf'], dtype=object)

In [103]:
# Import label encoder 
from sklearn import preprocessing 

# label_encoder object knows how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 

# Encode labels in column 'species'. 
data['cost-of-living-adjustment']= label_encoder.fit_transform(data['cost-of-living-adjustment']) 

data['cost-of-living-adjustment'].unique() 


array([0, 1, 2], dtype=int64)

In [86]:
data['cost-of-living-adjustment'].value_counts()
#data['cost-of-living-adjustment']= data['cost-of-living-adjustment'].fillna(mean1)


none    22
tcf      8
tc       7
Name: cost-of-living-adjustment, dtype: int64

In [106]:
data['pension'].value_counts()
data['pension'] = data['pension'].fillna('none')

data['pension']= label_encoder.fit_transform(data['pension']) 


In [109]:
data['education-allowance'].value_counts()

data['education-allowance'] = data['education-allowance'].fillna('no')
data['education-allowance']= label_encoder.fit_transform(data['education-allowance']) 


In [112]:
data['vacation'].value_counts()

data['vacation'] = data['vacation'].fillna('average')

data['vacation']= label_encoder.fit_transform(data['vacation']) 


In [115]:
data['longterm-disability-assistance'].value_counts()
data['longterm-disability-assistance'] = data['longterm-disability-assistance'].fillna('no')
data['longterm-disability-assistance']= label_encoder.fit_transform(data['longterm-disability-assistance']) 


In [118]:
data['bereavement-assistance'].value_counts()
data['bereavement-assistance'] = data['bereavement-assistance'].fillna('yes')

data['bereavement-assistance']= label_encoder.fit_transform(data['bereavement-assistance']) 


In [121]:
data['contribution-to-health-plan'].value_counts()
#mean7 = 20+9+8/3
data['contribution-to-health-plan'] = data['contribution-to-health-plan'].fillna('full')
data['contribution-to-health-plan']= label_encoder.fit_transform(data['contribution-to-health-plan']) 


In [123]:
data['contribution-to-dental-plan'].value_counts()
#mean7 = 20+9+8/3
data['contribution-to-dental-plan'] = data['contribution-to-dental-plan'].fillna('full')
data['contribution-to-dental-plan']= label_encoder.fit_transform(data['contribution-to-dental-plan']) 


In [124]:
data.describe()

duration  wage-increase-first-year  wage-increase-second-year  \
count  57.000000                 57.000000                  57.000000   
mean    2.157895                  3.807018                   3.977193   
std     0.701770                  1.358552                   1.043520   
min     1.000000                  2.000000                   2.000000   
25%     2.000000                  2.500000                   3.500000   
50%     2.000000                  4.000000                   4.000000   
75%     3.000000                  4.500000                   4.500000   
max     3.000000                  7.000000                   7.000000   

       wage-increase-third-year  cost-of-living-adjustment  working-hours  \
count                 57.000000                  57.000000      57.000000   
mean                   4.419298                   0.403509      38.035088   
std                    0.719980                   0.728493       2.367676   
min                    2.000000                   0.000000      27.000000   
25%                    4.600000                   0.000000      37.000000   
50%                    4.600000                   0.000000      38.000000   
75%                    4.600000                   1.000000      40.000000   
max                    5.100000                   2.000000      40.000000   

         pension  standby-pay  shift-differential  education-allowance  \
count  57.000000    57.000000           57.000000            57.000000   
mean    0.859649     7.912281            4.473684             0.175439   
std     0.515426     1.911251            3.354662             0.383723   
min     0.000000     2.000000            0.000000             0.000000   
25%     1.000000     8.000000            4.000000             0.000000   
50%     1.000000     8.000000            4.000000             0.000000   
75%     1.000000     8.000000            4.000000             0.000000   
max     2.000000    14.000000           25.000000             1.000000   

       statutory-holidays   vacation  longterm-disability-assistance  \
count           57.000000  57.000000                       57.000000   
mean            11.087719   0.877193                        0.350877   
std              1.214212   0.825274                        0.481487   
min              9.000000   0.000000                        0.000000   
25%             10.000000   0.000000                        0.000000   
50%             11.000000   1.000000                        0.000000   
75%             12.000000   2.000000                        1.000000   
max             15.000000   2.000000                        1.000000   

       contribution-to-dental-plan  bereavement-assistance  \
count                    57.000000               57.000000   
mean                      0.578947                0.947368   
std                       0.754685                0.225282   
min                       0.000000                0.000000   
25%                       0.000000                1.000000   
50%                       0.000000                1.000000   
75%                       1.000000                1.000000   
max                       2.000000                1.000000   

       contribution-to-health-plan  
count                    57.000000  
mean                      0.438596  
std                       0.732353  
min                       0.000000  
25%                       0.000000  
50%                       0.000000  
75%                       1.000000  
max                       2.000000

In [66]:
data['class'].value_counts()

good    37
bad     20
Name: class, dtype: int64

In [125]:
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import KFold, train_test_split, cross_val_score, cross_val_predict
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score

Model Decision Tree

In [126]:
X  = data.drop(['class'], axis =1)
y= data['class']
model = DecisionTreeClassifier(random_state=0)
#digunakan nilai K = 10
accuracy = cross_val_score(model, X, y, scoring='accuracy', cv = 5)
print(accuracy)

#Mencari nilai rata-rata akurasi K-Fold
print("Accuracy of Model with Cross Validation is:",accuracy.mean() * 100)

[ 0.83333333  0.83333333  0.81818182  0.81818182  0.90909091]
Accuracy of Model with Cross Validation is: 84.2424242424


In [137]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state= 2019)
model.fit(X_train, y_train)
y_pred = ensemble.predict(X_test)
from sklearn.metrics import precision_recall_fscore_support 
print('prec, recall, fscore : ', precision_recall_fscore_support(y_test, y_pred, average = 'micro'))

prec, recall, fscore :  (0.84210526315789469, 0.84210526315789469, 0.84210526315789469, None)


Model SVM

In [127]:
svc = SVC(kernel='rbf',gamma=0.1, C=1.0)
kfold = KFold(n_splits=10)
scores = cross_val_score(svc, X, y, cv=kfold, scoring='accuracy')
print("CROSS VALIDATION ACCURACY :", np.mean(scores))

CROSS VALIDATION ACCURACY : 0.896666666667


In [138]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state= 2019)
svc.fit(X_train, y_train)
y_pred = ensemble.predict(X_test)
from sklearn.metrics import precision_recall_fscore_support 
print('prec, recall, fscore : ', precision_recall_fscore_support(y_test, y_pred, average = 'micro'))

prec, recall, fscore :  (0.84210526315789469, 0.84210526315789469, 0.84210526315789469, None)


Model Naive Bayes

In [139]:
from sklearn.naive_bayes import GaussianNB
naive = GaussianNB()
naive.fit(X, y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state= 2019)
naive.fit(X_train, y_train)
y_pred = ensemble.predict(X_test)
from sklearn.metrics import precision_recall_fscore_support 
print('prec, recall, fscore : ', precision_recall_fscore_support(y_test, y_pred, average = 'micro'))

prec, recall, fscore :  (0.84210526315789469, 0.84210526315789469, 0.84210526315789469, None)


2b) k = 5 dengan random forest, adaboost dan gradient boosting

In [128]:
from sklearn import model_selection
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier

In [131]:
seed = 2019
kfold = model_selection.KFold(n_splits=5, random_state=seed) # create the sub models
estimators = []
model1 = RandomForestClassifier()
estimators.append(('cart', model1))
model2 = AdaBoostClassifier()
estimators.append(('Ada', model2))
model3 = GradientBoostingClassifier()
estimators.append(('GB', model3))
ensemble = VotingClassifier(estimators)
results = model_selection.cross_val_score(ensemble, X, y, cv=kfold)
print(results.mean())

0.824242424242


In [134]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state= 2019)
ensemble.fit(X_train, y_train)
y_pred = ensemble.predict(X_test)

In [136]:
from sklearn.metrics import precision_recall_fscore_support 
print('prec, recall, fscore : ', precision_recall_fscore_support(y_test, y_pred, average = 'micro'))

prec, recall, fscore :  (0.84210526315789469, 0.84210526315789469, 0.84210526315789469, None)
